GET http://localhost:3000

### GET ALL SONGS
GET http://localhost:3000/songs

### Create new song reqest
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "LNT Love NTKP",
    "artists": [1,2],
    "releasedDate": "2024-03-30",
    "duration": "03:03",
    "lyrics": "Hello hello"
}
### FIND SONG REQUEST
GET http://localhost:3000/songs/1

### UPDATE SONG REQUEST
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
    "title": "Lasting lover 2",
    "artists": ["LNT"],
    "releasedDate": "2024-03-30",
    "duration": "03:03",
    "lyrics": "Hello hello hello"
}

#### DELETE SONG REQUEST
DELETE  http://localhost:3000/songs/2

### PAGINATION SONG
GET http://localhost:3000/songs?page=1&limit=10

### CREATE PLAYLIST SONG BY USER
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "List Morning Song",
    "songIds": [3, 4],
    "userId": 1
}