GET http://localhost:3000

### GET ALL SONGS
GET http://localhost:3000/songs

### Create new song reqest
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "LNT Love NTKP",
    "artists": [1,2],
    "releasedDate": "2024-03-30",
    "duration": "03:03",
    "lyrics": "Hello hello"
}
### FIND SONG REQUEST
GET http://localhost:3000/songs/1

### UPDATE SONG REQUEST
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
    "title": "Lasting lover 2",
    "artists": ["LNT"],
    "releasedDate": "2024-03-30",
    "duration": "03:03",
    "lyrics": "Hello hello hello"
}

#### DELETE SONG REQUEST
DELETE  http://localhost:3000/songs/2

### PAGINATION SONG
GET http://localhost:3000/songs?page=1&limit=10

### CREATE PLAYLIST SONG BY USER
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "List Morning Song",
    "songIds": [3, 4],
    "userId": 1
}

### SIGNUP 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Ngọc Ngọc",
    "lastName": "Oanh",
    "email": "oanhngocngoc@gmail.com",
    "password": "123456789"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "oanhngocngoc@gmail.com",
    "password": "123456789"
}


## ACCESS TOKE: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9hbmhuZ29jbmdvY0BnbWFpbC5jb20iLCJzdWIiOjMsImlhdCI6MTcxMjA4MjM1MCwiZXhwIjoxNzEyMTY4NzUwLCJpc3MiOiJMTlQifQ.mpjDFXRrBlK2j4GoVi0P3MUs4MBcOiFuSHij-cshctU
####
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9hbmhuZ29jbmdvY0BnbWFpbC5jb20iLCJzdWIiOjMsImlhdCI6MTcxMjA4MjM1MCwiZXhwIjoxNzEyMTY4NzUwLCJpc3MiOiJMTlQifQ.mpjDFXRrBlK2j4GoVi0P3MUs4MBcOiFuSHij-cshctU
